### ISSUE TITLE
wrong center calculated?

### ISSUE THREAD

**Issue by fukemy** [yichizhang/YZPolygonHelper#3]
Let see this image:

![simulator screen shot - iphone 8 plus - 2018-09-16 at 19 33 23](https://user-images.githubusercontent.com/8202437/45596542-78cbb480-b9e7-11e8-9554-74384656077c.png)

**Comment by yichizhang** [comment]
> In the case of a single rigid body, the center of mass is fixed in relation to the body, and if the body has uniform density, it will be located at the centroid. The center of mass may be located outside the physical body, as is sometimes the case for hollow or open-shaped objects, such as a horseshoe.

[https://en.wikipedia.org/wiki/Center_of_mass](https://en.wikipedia.org/wiki/Center_of_mass)

**Comment by fukemy** [comment]
tks u. got it!
